// <auto-generated />
using Exercise5.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Exercise5.Migrations
{
    [DbContext(typeof(ApplicationDatabaseContext))]
    partial class ApplicationDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Exercise5.Model.Animal", b =>
                {
                    b.Property<long>("AnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("AnimalId");

                    b.ToTable("Animal");

                    b.HasData(
                        new
                        {
                            AnimalId = 1L,
                            Area = "Świat",
                            Category = "Ssak",
                            Description = "Najlepszy pies na świecie!",
                            Name = "Pies"
                        },
                        new
                        {
                            AnimalId = 2L,
                            Area = "Antarktyda",
                            Category = "Ptak",
                            Description = "Ptak nielot, ale pływa.",
                            Name = "Pingwin"
                        },
                        new
                        {
                            AnimalId = 3L,
                            Area = "Afryka, Azja",
                            Category = "Ssak",
                            Description = "Duży z trąbą.",
                            Name = "Słoń"
                        },
                        new
                        {
                            AnimalId = 4L,
                            Area = "Oceany",
                            Category = "Ryba",
                            Description = "Szczęki trzy!",
                            Name = "Rekin"
                        },
                        new
                        {
                            AnimalId = 5L,
                            Area = "Świat",
                            Category = "Ptak",
                            Description = "Ptak co fruwa.",
                            Name = "Orzeł"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
